services:

#Service mongoDB
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - ./db/mongo_data:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --auth --bind_ip_all
    networks:
      - api

  # Service de l'API Node.js
  api:
    build: .
    container_name: node_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      api:

networks:
  api:
